# Generated by Django 5.1.1 on 2025-01-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('uphno', models.IntegerField()),
                ('img', models.FileField(upload_to='')),
                ('usname', models.CharField(max_length=10, unique=True)),
                ('pwd', models.CharField(max_length=10)),
                ('addrs', models.CharField(max_length=100)),
                ('dist', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pncd', models.IntegerField()),
            ],
        ),
    ]
