# Generated by Django 5.1.1 on 2025-02-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_add_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='pro_id',
        ),
    ]
