# Generated by Django 5.1.1 on 2025-02-19 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_add_product_pro_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.IntegerField()),
                ('product_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_fname', models.CharField(max_length=20)),
                ('so_lname', models.CharField(max_length=20)),
                ('so_email', models.EmailField(max_length=254)),
                ('so_phone', models.IntegerField()),
                ('so_address', models.TextField()),
                ('so_district', models.CharField(max_length=20)),
                ('so_city', models.CharField(max_length=20)),
                ('so_pincode', models.IntegerField()),
                ('add_message', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Out For Shipping', 'Out For Shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=150)),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(max_length=150)),
                ('payment_id', models.CharField(max_length=150, null=True)),
                ('order_id', models.CharField(max_length=150)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_product')),
            ],
        ),
    ]
