# Generated by Django 5.1.1 on 2025-02-27 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=30)),
                ('status', models.IntegerField(default=0)),
                ('item_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.add_product')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register')),
            ],
        ),
    ]
