# Generated by Django 5.1.4 on 2025-03-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='d_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('df_name', models.CharField(max_length=10)),
                ('dl_name', models.CharField(max_length=15)),
                ('d_email', models.EmailField(max_length=254)),
                ('d_adrs', models.CharField(max_length=50)),
                ('d_phno', models.IntegerField()),
                ('d_img', models.FileField(upload_to='')),
                ('d_lcnc', models.FileField(upload_to='')),
                ('d_bio', models.FileField(upload_to='')),
                ('d_username', models.CharField(max_length=10, unique=True)),
                ('d_password', models.CharField(max_length=10)),
            ],
        ),
    ]
