# Generated by Django 5.1.4 on 2025-03-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_d_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.d_register'),
        ),
    ]
